import React from 'react';
import { Message, Role, MessageType } from '../types';

interface ChatMessageProps {
  message: Message;
}

const ChatMessage: React.FC<ChatMessageProps> = ({ message }) => {
  const isUser = message.role === Role.USER;

  return (
    <div className={`flex w-full ${isUser ? 'justify-end' : 'justify-start'} mb-6`}>
      <div className={`flex flex-col max-w-[85%] sm:max-w-[75%] ${isUser ? 'items-end' : 'items-start'}`}>
        
        {/* Header (Role Name) */}
        <span className="text-xs text-slate-400 mb-1 px-1">
          {isUser ? 'Anda' : 'Gemini'}
        </span>

        {/* Bubble */}
        <div 
          className={`px-4 py-3 rounded-2xl shadow-md ${
            isUser 
              ? 'bg-indigo-600 text-white rounded-tr-none' 
              : 'bg-slate-700 text-slate-100 rounded-tl-none border border-slate-600'
          }`}
        >
          {/* Render Attachments (Images) if User */}
          {message.attachments && message.attachments.length > 0 && (
            <div className="mb-3 flex flex-wrap gap-2">
              {message.attachments.map((att, idx) => (
                att.mimeType.startsWith('image/') ? (
                   <img 
                    key={idx} 
                    src={att.previewUrl} 
                    alt="Attachment" 
                    className="max-w-full h-auto max-h-60 rounded-lg border border-white/20"
                  />
                ) : (
                  <div key={idx} className="bg-white/10 p-2 rounded flex items-center text-sm">
                     <svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                      </svg>
                     {att.file.name}
                  </div>
                )
              ))}
            </div>
          )}

          {/* Render Text Content */}
          {message.type === MessageType.TEXT && (
             <div className="whitespace-pre-wrap leading-relaxed text-sm sm:text-base">
                {message.content}
             </div>
          )}
          
          {/* Render Error */}
           {message.type === MessageType.ERROR && (
             <div className="text-red-300 italic flex items-center">
                <svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 8v4m0 4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                </svg>
                {message.content}
             </div>
          )}

          {/* Render Generated Image */}
          {message.type === MessageType.IMAGE_GENERATION_RESULT && (
            <div className="mt-1">
                <img 
                  src={`data:image/png;base64,${message.content}`} 
                  alt="Generated by AI" 
                  className="w-full h-auto rounded-lg shadow-sm border border-slate-500"
                />
                <div className="mt-2 text-xs text-indigo-300 flex items-center justify-end">
                    <svg xmlns="http://www.w3.org/2000/svg" className="h-3 w-3 mr-1" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 3v4M3 5h4M6 17v4m-2-2h4m5-16l2.286 6.857L21 12l-5.714 2.143L13 21l-2.286-6.857L5 12l5.714-2.143L13 3z" />
                    </svg>
                    Gambar Dibuat oleh AI
                </div>
            </div>
          )}
        </div>
        
        {/* Timestamp */}
        <span className="text-[10px] text-slate-500 mt-1 px-1">
          {new Date(message.timestamp).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
        </span>
      </div>
    </div>
  );
};

export default ChatMessage;
